# config/packages/security.yaml
security:
    # Define how users are loaded (e.g., from database)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Password hashers configuration
    password_hashers:
        App\Entity\User: auto

    # Firewall configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            
            # Login form configuration
            form_login:
                login_path: app_connexion
                check_path: app_connexion
                default_target_path: app_home
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            
            # Logout configuration
            logout:
                path: app_logout
                target: app_home

    # Access control configuration
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }